services:
  db:
    image: postgres:16
    container_name: komobi-db
    environment:
      POSTGRES_USER: komobi
      POSTGRES_PASSWORD: komobi
      POSTGRES_DB: komobi
    ports:
      - "5432:5432"
    volumes:
      - komobi_pgdata:/var/lib/postgresql/data

volumes:
  komobi_pgdata:
